import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import Banner from './components/navbar/Banner'
import Rooms from './components/BodySection/Rooms'
import Footer from './components/footer/Footer'
import Bathroom from './components/BodySection/Bathroom'

const inter = Nunito({ subsets: ['latin'] },)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Banner />
        <Rooms />
        <Bathroom />
        <Footer />
        {children}</body>
    </html>
  )
}
